/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#7fd7fe",
        "tertiary-dim": "#70c9ef",
        "on-secondary-container": "#c9cdff",
        "surface-dim": "#0a0e14",
        "surface": "#0a0e14",
        "primary-container": "#00c1fd",
        "tertiary-fixed": "#7fd7fe",
        "secondary-fixed-dim": "#babfff",
        "outline": "#72757d",
        "secondary-fixed": "#cbceff",
        "on-background": "#f1f3fc",
        "on-primary-fixed-variant": "#004157",
        "background": "#0a0e14",
        "surface-container-lowest": "#000000",
        "surface-container-low": "#0f141a",
        "surface-container": "#151a21",
        "on-error-container": "#ffa8a3",
        "surface-bright": "#262c36",
        "error-container": "#9f0519",
        "on-tertiary": "#00536c",
        "on-surface-variant": "#a8abb3",
        "on-primary-container": "#00374b",
        "on-primary": "#004259",
        "secondary": "#929bfa",
        "secondary-dim": "#8d96f4",
        "inverse-primary": "#006789",
        "tertiary": "#a7e2ff",
        "on-error": "#490006",
        "on-secondary": "#0b1574",
        "primary-fixed-dim": "#00b2eb",
        "primary-dim": "#00b2eb",
        "tertiary-fixed-dim": "#70c9ef",
        "error": "#ff716c",
        "on-primary-fixed": "#001e2b",
        "error-dim": "#d7383b",
        "outline-variant": "#44484f",
        "on-surface": "#f1f3fc",
        "secondary-container": "#343d96",
        "inverse-on-surface": "#51555c",
        "on-tertiary-container": "#004a60",
        "on-tertiary-fixed-variant": "#00546d",
        "primary-fixed": "#00c1fd",
        "on-secondary-fixed-variant": "#3e47a0",
        "on-tertiary-fixed": "#003546",
        "surface-tint": "#61cdff",
        "surface-container-highest": "#20262f",
        "inverse-surface": "#f8f9ff",
        "on-secondary-fixed": "#1f2882",
        "surface-container-high": "#1b2028",
        "primary": "#61cdff",
        "surface-variant": "#20262f"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
